[package]
name = "rust-syntax-test"
version = "0.1.2"
authors = ["Zoltan Kovari"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/zkoevaari/rust-syntax-test.git"

[dependencies]
